name: HALD
channels:
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - opencv-python==4.10.0.84
      - fastai==2.7.18
      - gdown==5.2.0
      - timm==1.0.11
      - wandb==0.18.5
      - fast-pytorch-kmeans==0.2.2
      - einops
      - torchprofile
      - thop
      - uvicorn
      - fastapi
      - datasets
      - huggingface-hub
      - rich
      - tqdm
      - aim==3.29.1
      - aim-ui==3.29.1